spring:
  datasource:
   url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/customerdb}
    username: ${DATABASE_USER:customer_user}
    password: ${DATABASE_PASSWORD:customer_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
