spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transferdb
    username: transfer_user
    password: transaction_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
    show-sql: true
